name: Publish

on:
  push:
    branches: [main]

concurrency: publish-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - token: NPM_TOKEN
            url: 'https://registry.npmjs.org'
          - token: GITHUB_TOKEN
            url: 'https://npm.pkg.github.com'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: ${{ matrix.registry.url }}
          scope: '@byu-oit'
      - run: npm install
      - run: npm run test:coverage
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets[matrix.registry.token] }}
          registry: ${{ matrix.registry.url }}
          access: public
